import Head from "next/head";
import Header from "@/pages/common/Header";
import Container from "@/pages/common/Container";
import Footer from "@/pages/common/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>atti</title>
        <meta name="description" content="Generated by Next.js" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <script
          src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"
          strategy="beforeInteractive"
        ></script>
        {/*카카오 지도 API */}
      </Head>
      <Header />
      <Container />
      <Footer />
    </>
  );
}
