import Head from 'next/head';
import Header from './common/Header';
import Container from './common/Container';
import Footer from './common/Footer';
export default function Home() {
  return (
    <>
      <Head>
        <title>atti</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <Header />
      <Container />
      <Footer />
    </>
  );
}

